"""Utility functions for nanobot."""

from crabclaw.utils.helpers import ensure_dir, get_data_path, get_workspace_path
from crabclaw.utils.errors import (
    NanobotError,
    Result,
    ErrorCode,
    InvalidInputError,
    NotFoundError,
    PermissionDeniedError,
    TimeoutError,
    NetworkError,
    ExternalServiceError,
    ConfigurationError,
    ToolExecutionError,
    SecurityViolationError,
    RateLimitExceededError,
)
from crabclaw.utils.logging_config import setup_logging, logger, LogContext
from crabclaw.utils.metrics import metrics, Counter, Gauge, Histogram, Timer, count, timed, timed_async
from crabclaw.utils.cache import cache_manager, Cache, cached
from crabclaw.utils.plugin_system import plugin_registry, Plugin, PluginType, PluginMetadata
from crabclaw.utils.container import container, Container, Lifetime
from crabclaw.utils.http_pool import http_pool, HTTPClientPool, RateLimiter, RetryPolicy
from crabclaw.utils.testing import MockMessage, MockChannel, AsyncMock, FixtureBuilder
from crabclaw.utils.multimodal import (
    MediaType,
    MediaContent,
    MultimodalContentBuilder,
    VisionClient,
    TranscriptionClient,
    multimodal_builder,
)
from crabclaw.utils.microservices import (
    ServiceStatus,
    ServiceHealth,
    Service,
    ServiceRegistry,
    HealthChecker,
    LifecycleManager,
    GracefulShutdown,
    SignalHandler,
    service_registry,
    lifecycle_manager,
    graceful_shutdown,
    service_context,
)

__all__ = [
    "ensure_dir",
    "get_workspace_path",
    "get_data_path",
    "NanobotError",
    "Result",
    "ErrorCode",
    "InvalidInputError",
    "NotFoundError",
    "PermissionDeniedError",
    "TimeoutError",
    "NetworkError",
    "ExternalServiceError",
    "ConfigurationError",
    "ToolExecutionError",
    "SecurityViolationError",
    "RateLimitExceededError",
    "setup_logging",
    "logger",
    "LogContext",
    "metrics",
    "Counter",
    "Gauge",
    "Histogram",
    "Timer",
    "count",
    "timed",
    "timed_async",
    "cache_manager",
    "Cache",
    "cached",
    "plugin_registry",
    "Plugin",
    "PluginType",
    "PluginMetadata",
    "container",
    "Container",
    "Lifetime",
    "http_pool",
    "HTTPClientPool",
    "RateLimiter",
    "RetryPolicy",
    "MockMessage",
    "MockChannel",
    "AsyncMock",
    "FixtureBuilder",
    "MediaType",
    "MediaContent",
    "MultimodalContentBuilder",
    "VisionClient",
    "TranscriptionClient",
    "multimodal_builder",
    "ServiceStatus",
    "ServiceHealth",
    "Service",
    "ServiceRegistry",
    "HealthChecker",
    "LifecycleManager",
    "GracefulShutdown",
    "SignalHandler",
    "service_registry",
    "lifecycle_manager",
    "graceful_shutdown",
    "service_context",
]
