"""Utility functions for Crabclaw."""

from crabclaw.utils.cache import Cache, cache_manager, cached
from crabclaw.utils.container import Container, Lifetime, container
from crabclaw.utils.errors import (
    ConfigurationError,
    CrabclawError,
    ErrorCode,
    ExternalServiceError,
    InvalidInputError,
    NetworkError,
    NotFoundError,
    PermissionDeniedError,
    RateLimitExceededError,
    Result,
    SecurityViolationError,
    TimeoutError,
    ToolExecutionError,
)
from crabclaw.utils.helpers import ensure_dir, get_data_path, get_workspace_path
from crabclaw.utils.http_pool import HTTPClientPool, RateLimiter, RetryPolicy, http_pool
from crabclaw.utils.logging_config import LogContext, logger, setup_logging
from crabclaw.utils.metrics import (
    Counter,
    Gauge,
    Histogram,
    Timer,
    count,
    metrics,
    timed,
    timed_async,
)
from crabclaw.utils.microservices import (
    GracefulShutdown,
    HealthChecker,
    LifecycleManager,
    Service,
    ServiceHealth,
    ServiceRegistry,
    ServiceStatus,
    SignalHandler,
    graceful_shutdown,
    lifecycle_manager,
    service_context,
    service_registry,
)
from crabclaw.utils.multimodal import (
    MediaContent,
    MediaType,
    MultimodalContentBuilder,
    TranscriptionClient,
    VisionClient,
    multimodal_builder,
)
from crabclaw.utils.plugin_system import Plugin, PluginMetadata, PluginType, plugin_registry
from crabclaw.utils.testing import AsyncMock, FixtureBuilder, MockChannel, MockMessage

__all__ = [
    "ensure_dir",
    "get_workspace_path",
    "get_data_path",
    "CrabclawError",
    "Result",
    "ErrorCode",
    "InvalidInputError",
    "NotFoundError",
    "PermissionDeniedError",
    "TimeoutError",
    "NetworkError",
    "ExternalServiceError",
    "ConfigurationError",
    "ToolExecutionError",
    "SecurityViolationError",
    "RateLimitExceededError",
    "setup_logging",
    "logger",
    "LogContext",
    "metrics",
    "Counter",
    "Gauge",
    "Histogram",
    "Timer",
    "count",
    "timed",
    "timed_async",
    "cache_manager",
    "Cache",
    "cached",
    "plugin_registry",
    "Plugin",
    "PluginType",
    "PluginMetadata",
    "container",
    "Container",
    "Lifetime",
    "http_pool",
    "HTTPClientPool",
    "RateLimiter",
    "RetryPolicy",
    "MockMessage",
    "MockChannel",
    "AsyncMock",
    "FixtureBuilder",
    "MediaType",
    "MediaContent",
    "MultimodalContentBuilder",
    "VisionClient",
    "TranscriptionClient",
    "multimodal_builder",
    "ServiceStatus",
    "ServiceHealth",
    "Service",
    "ServiceRegistry",
    "HealthChecker",
    "LifecycleManager",
    "GracefulShutdown",
    "SignalHandler",
    "service_registry",
    "lifecycle_manager",
    "graceful_shutdown",
    "service_context",
]
