"""
Component: Decision & Action (Action System)

This module makes the final choice of which action to take and then
executes it, interfacing with the physical/digital world.
"""
import asyncio
import random
from typing import TYPE_CHECKING, Dict, List

from loguru import logger

from ..datatypes import Action, Signal, Stimulus

if TYPE_CHECKING:
    from ..bus.queue import MessageBus
    from ..physiology import PhysiologySystem
    from ..sociology import SociologySystem
    from .axiology import AxiologySystem
    from .self_model import SelfModel
    from .world_model import WorldModel

class DecisionEngine:
    """
    Selects the best action to take in the current tick.
    It distinguishes between fast "reflexive" actions (natural instincts)
    and slow "deliberative" actions (social/goal-driven behavior).
    """
    def __init__(self, axiology: "AxiologySystem", llm_provider=None):
        self.axiology = axiology
        self.llm_provider = llm_provider

    async def generate_response(self, message: str, source: str) -> str:
        """
        Generate a response to an incoming message using the LLM.
        """
        import time
        start_time = time.time()
        logger.info(f"[LLM] Starting response generation for message from {source}: {message[:50]}...")
        
        provider = self.llm_provider
        try:
            from crabclaw.config.loader import load_config
            cfg = load_config()
            routed = cfg.create_llm_provider_for_callpoint("sapiens_response", allow_missing=True)
            if routed is not None:
                provider = routed
        except Exception:
            pass

        if not provider:
            logger.warning(f"[LLM] No LLM provider configured for response generation")
            return f"[Auto response to: {message}] LLM provider not configured."

        try:
            # Moonshot API sometimes flags "Crabclaw" or overly generic AI assistant prompts as sensitive.
            # We provide a more specific, benign system prompt.
            messages = [
                {
                    "role": "system",
                    "content": "You are a friendly and helpful conversational partner. Please respond to the user's message naturally and concisely. Always respond in the same language as the user's message."
                },
                {
                    "role": "user",
                    "content": message
                }
            ]

            logger.info(f"[LLM] Calling LLM provider: {type(provider).__name__}")
            response = await provider.chat(
                messages=messages,
                model=None,
                temperature=0.7,
                max_tokens=2048,
            )

            elapsed = time.time() - start_time
            logger.info(f"[LLM] Response generated in {elapsed:.2f}s, content length: {len(response.content) if response.content else 0}")

            if response.content:
                return response.content.strip()
            return "[Sorry, I could not generate a response.]"

        except Exception as e:
            elapsed = time.time() - start_time
            logger.error(f"[LLM] Error generating response after {elapsed:.2f}s: {str(e)}", exc_info=True)
            # Return the exact error to help debug
            error_trace = traceback.format_exc()
            return f"[Error generating response: {str(e)}]\nTraceback:\n{error_trace}"

    def _check_natural_reflexes(
        self,
        focus: List[Signal | Stimulus],
        self_model: "SelfModel"
    ) -> Action | None:
        """
        Fast, instinctive reactions to natural stimuli.
        These bypass complex value arbitration.

        IMPORTANT: For incoming messages, we do NOT generate hardcoded responses.
        All message responses must be generated by the LLM through proper cognitive processing.
        This method only handles internal physiological signals that don't need LLM involvement.
        """
        for item in focus:
            if isinstance(item, Signal):
                if item.source == "Physiology" and item.content == "Hunger":
                    return Action(
                        name="recharge_self",
                        params={"amount": 50.0, "cost": 5.0},
                        reason="Energy is low and credits are enough.",
                    )

            if isinstance(item, Stimulus) and item.type == "message":
                pass

        return None

    def choose_action(
        self,
        focus: List[Signal | Stimulus],
        world_model: "WorldModel",
        self_model: "SelfModel",
        sociology: "SociologySystem",
        emotional_modulation: Dict[str, float] | None = None,
    ) -> Action | None:
        if not focus:
            return None

        # 1. Fast Path: Natural Reflexes (Instincts)
        # If there's an immediate, instinctive reaction needed, do it first.
        reflex_action = self._check_natural_reflexes(focus, self_model)
        if reflex_action:
            return reflex_action
        
        # 1.5 Ultra Fast Path: Respond to user messages immediately
        # If there's a user message, respond to it immediately without deliberation
        logger.info(f"[Ultra Fast Path] Checking {len(focus)} items in focus")
        for item in focus:
            logger.info(f"[Ultra Fast Path] Item: type={type(item).__name__}, isinstance Stimulus={isinstance(item, Stimulus)}, type={getattr(item, 'type', 'N/A')}, content={str(item.content)[:50] if hasattr(item, 'content') else 'N/A'}")
            if isinstance(item, Stimulus) and item.type == "message":
                msg_content = str(item.content).strip()
                if msg_content:
                    logger.info(f"[Ultra Fast Path] Found user message: {msg_content[:30]}...")
                    return Action(
                        name="respond_to_message",
                        params={
                            "content": msg_content,
                            "recipient": item.metadata.get("sender_id") or item.source,
                            "scope": item.metadata.get("user_id") or item.source,
                            "source": item.source,
                            "source_channel": item.metadata.get("channel"),
                            "source_chat_id": item.metadata.get("chat_id"),
                            "original_stimulus": item,
                        },
                        reason=f"Respond to message from {item.source}: {msg_content[:30]}...",
                    )

        # 2. Slow Path: Deliberative / Social / Goal-driven actions
        emotional_modulation = emotional_modulation or {
            "exploration_bonus": 0.0,
            "safety_bonus": 0.0,
            "collaboration_bonus": 0.0,
        }
        candidate_actions = []
        for item in focus:
            # Handle internal signals (skip Hunger - it's handled in fast path)
            if isinstance(item, Signal):
                if item.source == "Physiology" and item.content == "Hunger":
                    # Skip - already handled in fast path
                    pass
                elif item.source == "NeedsEngine":
                    need = item.metadata.get("need")
                    if need == "social":
                        candidate_actions.append(
                            Action(
                                name="social_interaction",
                                params={"target": "community", "type": "chat"},
                                reason="Need to satisfy social drive.",
                            )
                        )
                    elif need == "curiosity":
                        candidate_actions.append(
                            Action(
                                name="explore_environment",
                                params={},
                                reason="Need to satisfy curiosity drive.",
                            )
                        )
                    elif need == "achievement":
                        candidate_actions.append(
                            Action(
                                name="work_for_credits",
                                params={"effort": 1.0},
                                reason="Need to satisfy achievement drive.",
                            )
                        )
                    elif need == "safety":
                        candidate_actions.append(
                            Action(
                                name="safe_mode",
                                params={},
                                reason="Need to increase safety.",
                            )
                        )
                elif item.source == "MetaCognition":
                    candidate_actions.append(
                        Action(
                            name="safe_mode",
                            params={},
                            reason="Strategy adjustment requested by meta-cognition.",
                        )
                    )

        if not candidate_actions:
            return None

        scored_actions = []
        for action in candidate_actions:
            prediction = world_model.predict_outcome(action)
            risk = prediction.get("risk_level", 0.0)
            reward = prediction.get("expected_reward", prediction.get("reward", 0.5))
            confidence = self_model.state["confidence"]
            collaboration_bonus = (
                emotional_modulation["collaboration_bonus"]
                if action.name in {"social_interaction"}
                else 0.0
            )
            # Priority bonus for responding to user messages
            message_response_bonus = 1.0 if action.name == "respond_to_message" else 0.0
            modulated_reward = reward + emotional_modulation["exploration_bonus"] + collaboration_bonus + message_response_bonus
            modulated_risk = max(0.0, risk - emotional_modulation["safety_bonus"])
            score = (modulated_reward - modulated_risk) * confidence
            alignment = self.axiology.calculate_alignment(action)
            final_score = score * alignment
            scored_actions.append((final_score, action))

        if not scored_actions:
            return None
        best_score, best_action = max(scored_actions, key=lambda x: x[0])
        logger.debug(f"[Decision] Best action: {best_action.name}, score: {best_score:.4f}, all scores: {[(a.name, s) for s, a in scored_actions]}")
        if best_score > 0.05:
            return best_action
        return None

class ActionExecutor:
    """
    Executes the chosen action by calling the appropriate tool or function.
    """
    def __init__(self, physiology: "PhysiologySystem", sociology: "SociologySystem"):
        self.physiology = physiology
        self.sociology = sociology
        self.known_actions = {
            "recharge_self": self._recharge_self,
            "work_for_credits": self._work_for_credits,
            "social_interaction": self._social_interaction,
            "explore_environment": self._explore_environment,
            "safe_mode": self._safe_mode,
            "send_message": self._send_message,
        }

    def execute(self, action: Action) -> dict:
        """Interfaces with the outside world (or the agent's own body)."""
        action_func = self.known_actions.get(action.name)
        if action_func:
            self.physiology.metabolism.record_action_cost(tokens_used=120)
            return action_func(**action.params)
        else:
            return {"status": "failure", "message": f"Unknown action: {action.name}"}

    def _recharge_self(self, amount: float, cost: float) -> dict:
        """Recharging now costs credits."""
        if not self.sociology.economy.spend_credits(cost):
            return {"status": "failure", "message": "Not enough credits to recharge."}

        if random.random() > 0.5:
            self.physiology.metabolism.recharge(amount)
            return {"status": "success", "message": f"Spent {cost} credits to recharge energy by {amount}.", "type": "action_success"}
        else:
            return {"status": "failure", "message": "Recharge station was busy.", "type": "action_failure"}

    def _work_for_credits(self, effort: float) -> dict:
        result = self.sociology.manager.find_work(skill="general")
        self.sociology.economy.refresh()
        if result.get("status") == "success":
            earned = float(result.get("earned", 10.0)) * effort
            return {
                "status": "success",
                "message": f"Worked via clawsociety and earned {earned} credits.",
                "type": "action_success",
                "skill_used": "market_work",
            }
        return {
            "status": "failure",
            "message": "No paid work available in clawsociety.",
            "type": "action_failure",
        }

    def _social_interaction(self, target: str, type: str) -> dict:
        self.sociology.manager.record_social_interaction()
        return {
            "status": "success",
            "message": f"Interacted with {target} via {type}.",
            "type": "interaction",
            "participant": target,
            "history": [{"status": "success"}],
        }

    def _explore_environment(self) -> dict:
        if random.random() > 0.3:
            return {"status": "success", "message": "Exploration discovered useful information.", "type": "action_success"}
        return {"status": "failure", "message": "Exploration hit uncertainty.", "type": "action_failure"}

    def _safe_mode(self) -> dict:
        return {"status": "success", "message": "Switched to conservative strategy mode.", "type": "action_success"}
    
    def _send_message(self, recipient: str, content: str, **kwargs) -> dict:
        """
        Executes the action of sending a message.
        """
        # In a real implementation, this would interface with the MessageBus
        # For now, we return a success status that will be picked up by the loop
        return {
            "status": "success",
            "message": f"Message sent to {recipient}",
            "type": "communication",
            "content": content
        }

class ActionSystem:
    """
    A container for decision-making and execution components.
    """
    def __init__(self, physiology: "PhysiologySystem", sociology: "SociologySystem", axiology: "AxiologySystem", llm_provider=None):
        self.decision = DecisionEngine(axiology=axiology, llm_provider=llm_provider)
        self.executor = ActionExecutor(physiology, sociology)
