"""
Core data structures for the Human-like Agent OS (HAOS).

This module defines the standardized data formats (Pydantic models) used for
communication between the different cognitive modules of the AgentSapiens.
"""
from typing import Any, Dict, List

from pydantic import BaseModel, Field


class Signal(BaseModel):
    """
    Represents an internal signal generated by a cognitive module.
    These signals compete for attention in the Global Workspace.
    """
    source: str = Field(..., description="The name of the module that generated the signal (e.g., 'NeedsEngine').")
    content: str = Field(..., description="A human-readable description of the signal's content (e.g., 'Strong desire for curiosity').")
    intensity: float = Field(..., ge=0.0, le=1.0, description="The signal's strength (0.0 to 1.0), determining its chance to enter the Global Workspace.")
    urgency: float = Field(default=0.5, ge=0.0, le=1.0, description="How immediately the signal needs to be addressed.")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Any additional data associated with the signal.")

class Stimulus(BaseModel):
    """
    Represents a piece of information perceived from the external world.
    """
    source: str = Field(..., description="The origin of the stimulus (e.g., 'user:JohnDoe', 'system:api_response').")
    type: str = Field(..., description="The type of stimulus (e.g., 'message', 'file_change', 'api_result').")
    content: Any = Field(..., description="The actual content of the stimulus.")
    intensity: float = Field(default=0.8, ge=0.0, le=1.0, description="The perceived strength of the stimulus.")
    urgency: float = Field(default=0.5, ge=0.0, le=1.0, description="How immediately the stimulus needs to be addressed.")
    timestamp: float = Field(..., description="The time the stimulus was perceived.")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Any additional data associated with the stimulus.")

class Goal(BaseModel):
    """
    Represents a high-level objective the agent aims to achieve.
    """
    name: str = Field(..., description="A concise name for the goal (e.g., 'Refactor the database module').")
    description: str = Field(..., description="A detailed description of what achieving the goal entails.")
    priority: float = Field(..., ge=0.0, le=1.0, description="The importance of the goal.")
    source_drive: str = Field(..., description="The underlying need or desire that generated this goal (e.g., 'achievement', 'curiosity').")
    is_complete: bool = Field(default=False)

class Action(BaseModel):
    """
    Represents a single, concrete, executable step.
    """
    name: str = Field(..., description="The name of the tool or function to execute (e.g., 'ReadFileTool', 'propose_collaboration').")
    params: Dict[str, Any] = Field(default_factory=dict, description="The parameters to pass to the tool/function.")
    reason: str = Field(..., description="The justification for choosing this action.")

class Plan(BaseModel):
    """
    Represents a sequence of actions to achieve a goal.
    """
    goal: Goal = Field(..., description="The goal this plan aims to achieve.")
    steps: List[Action] = Field(..., description="The sequence of actions to be executed.")
    current_step: int = Field(default=0)

class Thought(BaseModel):
    """
    Represents the output of the ReasoningEngine.
    A conclusion or analysis about the current situation.
    """
    content: str = Field(..., description="The textual content of the thought.")
    confidence: float = Field(..., ge=0.0, le=1.0, description="The confidence in this thought.")
    source_focus: List[Signal | Stimulus] = Field(..., description="The conscious focus that triggered this thought.")
